namespace FontStashSharp.TrueType;

public enum TrueTypePlatformSpecificId : ushort
{
	/* Unicode */
	Version1_0 = 0,
	Version1_1 = 1,
	ISO10646_1993 = 2,
	Unicode2_0_BmpOnly = 3,
	Unicode2_0_NonBmpAllowed = 4,

	/* Macintosh */
	Roman = 0,
	Japanese = 1,
	TraditionalChinese = 2,
	Korean = 3,
	Arabic = 4,
	Hebrew = 5,
	Greek = 6,
	Russian = 7,
	RSymbol = 8,
	Devanagari = 9,
	Gurmukhi = 10,
	Gujarati = 11,
	Oriya = 12,
	Bengali = 13,
	Tamil = 14,
	Telugu = 15,
	Kannada = 16,
	Malayalam = 17,
	Sinhalese = 18,
	Burmese = 19,
	Khmer = 20,
	Thai = 21,
	Laotian = 22,
	Georgian = 23,
	Armenian = 24,
	SimplifiedChinese = 25,
	Tibetan = 26,
	Mongolian = 27,
	Geez = 28,
	Slavic = 29,
	Vietnamese = 30,
	Sindhi = 31,
	Uninterpreted = 32,
}
