namespace FontStashSharp.TrueType;

public enum TrueTypeNameId : ushort
{
	CopyrightNotice = 0,
	FontFamily = 1,
	FontSubfamily = 2,
	UniqueSubfamilyIdentification = 3,
	FullName = 4,
	VersionOfNameTable = 5,
	PostScriptNameOfFont = 6,
	TrademarkNotice = 7,
	ManufacturerName = 8,
	Designer = 9,
	Description = 10,
	UrlOfFontVendor = 11,
	UrlOfFontDesigner = 12,
	LicenseDescription = 13,
	LicenseUrl = 14,
	Reserved = 15,
	PreferredFamily = 16,
	PreferredSubfamily = 17,
	CompatibleFull = 18,
	SampleText = 19,
	OpenType0 = 20,
	OpenType1 = 21,
	OpenType2 = 22,
	OpenType3 = 23,
	OpenType4 = 24,
	VariationsPostScriptNamePrefix = 25,
}
